.PHONY: all build run clean

all:
	@echo "Build and execute program with === cargo run ==="
	@cd hello_world && cargo run

build:
	@echo "Build the program with === cargo build ==="
	@cd hello_world && cargo build

run:
	@echo "Run the compiled program with === ./target/debug/* ==="
	@cd hello_world && ./target/debug/hello_world

clean:
	@echo "Clean up using === cargo clean ==="
	@cd hello_world && cargo clean